-- AlterTable
ALTER TABLE `banks` ADD COLUMN `type` ENUM('SALARY_ACCOUNT', 'CURRENT_ACCOUNT', 'SAVINGS_ACCOUNT', 'INVESTMENT', 'CREDIT_CARD', 'DIGITAL_WALLET', 'OTHER') NOT NULL DEFAULT 'CURRENT_ACCOUNT';
